name: Build Node App Image

on:
  push:
    tags: [ "v*.*.*-*" ]
  pull_request:
    types: [ "opened" ]
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TAG: ${{ github.ref_name }}

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 9.x
        uses: actions/setup-node@v3
        with:
          node-version: 9.x
          cache: 'npm'
      
      - name: Install dependancy
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-image:
    needs: test-app
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.GITHUB_TAG}}